# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

EpiIndicatorsC <- function(date, f, g, s_min = -10L, s_max = 25L, wr = 5000, ws = 50, r_init = -1e6, r_end = -1e6, s_init = -1e6, s_end = -1e6) {
    .Call(`_EpiInvert_EpiIndicatorsC`, date, f, g, s_min, s_max, wr, ws, r_init, r_end, s_init, s_end)
}

joint_indicators_by_dateC <- function(date0, i0, date1, i1) {
    .Call(`_EpiInvert_joint_indicators_by_dateC`, date0, i0, date1, i1)
}

EpiInvertForecastC <- function(i_original, i_restored, last_incidence_date, q_bias, i_restored_database, type, NumberForecastAdditionalDays = 0L, trend_sentiment = 0) {
    .Call(`_EpiInvert_EpiInvertForecastC`, i_original, i_restored, last_incidence_date, q_bias, i_restored_database, type, NumberForecastAdditionalDays, trend_sentiment)
}

EpiInvertC <- function(i_original0, last_incidence_date, festive_days, si_distr0, shift_si_distr = 0L, max_time_interval = 50L, mean_si = 12.267893, sd_si = 5.667547, shift_si = -5., Rt_regularization_weight = 5., seasonality_regularization_weight = 5., incidence_weekly_aggregated = FALSE, NweeksToKeepIncidenceSum = 2L) {
    .Call(`_EpiInvert_EpiInvertC`, i_original0, last_incidence_date, festive_days, si_distr0, shift_si_distr, max_time_interval, mean_si, sd_si, shift_si, Rt_regularization_weight, seasonality_regularization_weight, incidence_weekly_aggregated, NweeksToKeepIncidenceSum)
}

